"""empty message

Revision ID: 754253afa3b0
Revises: 
Create Date: 2018-11-05 23:39:45.950712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754253afa3b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('languages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('developer', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.create_table('messages',
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=140), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
